# Generated by Django 2.2 on 2024-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('classified', models.CharField(blank=True, max_length=200)),
                ('uploaded', models.DateTimeField()),
            ],
        ),
    ]
